import {
  Tag,
  ShoppingCart,
  Coffee,
  Home,
  Car,
  Bus,
  Train,
  Heart,
  Pill,
  DollarSign,
  Gift,
  CreditCard,
  Briefcase,
  Utensils,
  Gamepad2,
  Shirt,
  Plane,
  Smartphone,
  Book,
  Scissors,
  Baby,
  Bike,
  Dumbbell,
  Laptop,
  Tv,
  GraduationCap,
  Wine,
  Music,
  Ticket,
  Wallet,
  PiggyBank,
  Landmark,
  Building2,
  TrendingUp,
  TrendingDown,
  Fuel,
  Wrench,
  Stethoscope,
  PawPrint,
  Trees,
  Umbrella,
  Wifi,
  Camera,
  Film,
  Headphones,
  ShoppingBag,
  Package,
  Truck,
  Coins,
  Banknote,
  ReceiptText,
  Droplet,
  Zap,
  Flame,
  Trash2,
  Paintbrush,
  Guitar,
  BookOpen,
  Newspaper,
  Users,
  HeartHandshake,
  HandCoins,
  Cat,
  Dog,
  MapPin,
} from "lucide-react";

// Fuente única de íconos y colores para categorías: la usan tanto el picker
// mobile (IconColorPickerSheet) como los inputs desktop (IconInput/ColorInput),
// para que nunca queden desincronizados entre breakpoints.
export const CATEGORY_ICONS = [
  { component: Tag, englishName: "Tag" },
  { component: ShoppingCart, englishName: "ShoppingCart" },
  { component: Coffee, englishName: "Coffee" },
  { component: Home, englishName: "Home" },
  { component: Car, englishName: "Car" },
  { component: Bus, englishName: "Bus" },
  { component: Train, englishName: "Train" },
  { component: Heart, englishName: "Heart" },
  { component: Pill, englishName: "Pill" },
  { component: DollarSign, englishName: "DollarSign" },
  { component: Gift, englishName: "Gift" },
  { component: CreditCard, englishName: "CreditCard" },
  { component: Briefcase, englishName: "Briefcase" },
  { component: Utensils, englishName: "Utensils" },
  { component: Gamepad2, englishName: "Gamepad2" },
  { component: Shirt, englishName: "Shirt" },
  { component: Plane, englishName: "Plane" },
  { component: Smartphone, englishName: "Smartphone" },
  { component: Book, englishName: "Book" },
  { component: Scissors, englishName: "Scissors" },
  { component: Baby, englishName: "Baby" },
  { component: Bike, englishName: "Bike" },
  { component: Dumbbell, englishName: "Dumbbell" },
  { component: Laptop, englishName: "Laptop" },
  { component: Tv, englishName: "Tv" },
  { component: GraduationCap, englishName: "GraduationCap" },
  { component: Wine, englishName: "Wine" },
  { component: Music, englishName: "Music" },
  { component: Ticket, englishName: "Ticket" },
  { component: Wallet, englishName: "Wallet" },
  { component: PiggyBank, englishName: "PiggyBank" },
  { component: Landmark, englishName: "Landmark" },
  { component: Building2, englishName: "Building2" },
  { component: TrendingUp, englishName: "TrendingUp" },
  { component: TrendingDown, englishName: "TrendingDown" },
  { component: Fuel, englishName: "Fuel" },
  { component: Wrench, englishName: "Wrench" },
  { component: Stethoscope, englishName: "Stethoscope" },
  { component: PawPrint, englishName: "PawPrint" },
  { component: Trees, englishName: "Trees" },
  { component: Umbrella, englishName: "Umbrella" },
  { component: Wifi, englishName: "Wifi" },
  { component: Camera, englishName: "Camera" },
  { component: Film, englishName: "Film" },
  { component: Headphones, englishName: "Headphones" },
  { component: ShoppingBag, englishName: "ShoppingBag" },
  { component: Package, englishName: "Package" },
  { component: Truck, englishName: "Truck" },
  { component: Coins, englishName: "Coins" },
  { component: Banknote, englishName: "Banknote" },
  { component: ReceiptText, englishName: "ReceiptText" },
  { component: Droplet, englishName: "Droplet" },
  { component: Zap, englishName: "Zap" },
  { component: Flame, englishName: "Flame" },
  { component: Trash2, englishName: "Trash2" },
  { component: Paintbrush, englishName: "Paintbrush" },
  { component: Guitar, englishName: "Guitar" },
  { component: BookOpen, englishName: "BookOpen" },
  { component: Newspaper, englishName: "Newspaper" },
  { component: Users, englishName: "Users" },
  { component: HeartHandshake, englishName: "HeartHandshake" },
  { component: HandCoins, englishName: "HandCoins" },
  { component: Cat, englishName: "Cat" },
  { component: Dog, englishName: "Dog" },
  { component: MapPin, englishName: "MapPin" },
];

export const CATEGORY_COLORS = [
  "#ef4444", "#f97316", "#f59e0b", "#ca8a04", "#84cc16",
  "#65a30d", "#22c55e", "#10b981", "#14b8a6", "#06b6d4",
  "#0ea5e9", "#3b82f6", "#6366f1", "#8b5cf6", "#a855f7",
  "#d946ef", "#ec4899", "#f43f5e", "#fb7185", "#fda4af",
  "#94a3b8", "#78716c", "#57534e", "#44403c", "#1c1917",
  "#b91c1c", "#7c2d12", "#9a3412", "#c2410c", "#a16207",
];
